version: "3.2"

services:
  php:
    build:
      context: './docker/php/'
      args:
       PHP_VERSION: 7.0
    networks:
      - backend
    volumes:
      - ./src/:/var/www/html/
    container_name: php_vsql

  apache:
    build:
      context: './docker/apache/'
      args:
       APACHE_VERSION: 2.4.32
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./src/:/var/www/html/
      - ./docker/vhosts/default.conf:/usr/local/apache2/conf/demo.apache.conf

    container_name: apache_vsql

networks:
  frontend:
  backend:
volumes:
    data:
