version: "3.2"

services:
  
  php:
    build:
      context: './docker/php/'
      args:
       PHP_VERSION: 7.0
    networks:
      - backend
    volumes:
      - ./src/:/var/www/html/
    container_name: phpvsql

  apache:
    build:
      context: './docker/apache/'
      args:
       APACHE_VERSION: 2.4.32
    depends_on:
      - php
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./src/:/var/www/html/
      - ./docker/vhosts/default.conf:/usr/local/apache2/conf/demo.apache.conf
    container_name: apachevsql

  mysql:
    image: mysql/mysql-server:5.5
    restart: always
    ports:
      - "9906:3306"
    volumes:
      - "/docker/mysql:/var/lib/mysql"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbtest
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: 172.21.0.2
    container_name: mysqlvsql

networks:
  backend:
